CREATE PROCEDURE Exam_info
@MSSV CHAR(7),
@MSMH CHAR(9),
@SOLAN INT OUT,
@DIEMMAX DECIMAL(5, 2) OUT,
@DIEMTB DECIMAL(5, 2) OUT
AS
SELECT @SOLAN = COUNT(*), @DIEMMAX = MAX(DIEM), @DIEMTB = AVG(DIEM) FROM HOC H 
JOIN LOP L ON H.malop = L.malop
WHERE MSSV = @MSSV AND MSMH = @MSMH

SELECT COUNT(*), MAX(DIEM), AVG(DIEM) FROM HOC H JOIN LOP L ON H.malop = L.malop
WHERE MSSV = '2330004' AND MSSH = 'IT01012'


-- DECLARE EXEC
DECLARE @SL INT
DECLARE @DMAX DECIMAL(5, 2)
DECLARE @DTB DECIMAL(5, 2)
EXEC DIEM_INFO '230004', 'IT01012', @SL OUT, @DMAX OUT, @DTB OUT
PRINT @SL
PRINT @DMAX
PRINT @DTB


-- Procedure to find the number of students in the class, the number of students who pass and the number of student who fail
CREATE PROCEDURE Class_Info
@MALOP 
@SS OUT
@SVDau OUT
@SVRot OUT
AS

SELECT @SS = COUNT(MSSV)
FROM HOC
WHERE @MALOP = MALOP

SELECT @SOSVDAU = COUNT(MSSV)
FROM HOC
WHERE MALOP = @MALOP AND DIEM >= 5

SELECT @SOSVROT = COUNT(MSSV)
WHERE MALOP = @MALOP AND DIEM < 5

DECLARE @S1 INT
DECLARE @S2 INT
DECLARE @S3 INT
EXEC Class_Info 
